---

#
# This script automates installation process in:
# https://www.nsnam.org/docs/dce/release/1.5/manual/html/getting-started.html
# for NS3/DCE
# and
# https://plus.google.com/+HajimeTazaki/posts/1QUmR3n3vNA
# for MPTCP
#

- name: setup NS3 with DCE for net-next-sim and mptcp kernel
  hosts: all
  vars:
    src: "{{ ansible_env.HOME }}/deployed"
    bake_env:
       BAKE_HOME: "{{ src }}/bake"
       PATH: "{{ src }}/bake:{{ ansible_env.PATH }}"
       PYTHONPATH: "{{ ansible_env.PYTHONPATH }}:{{ src }}/bake"
    dce_dir: "{{ ansible_env.HOME }}/deployed/dce/"
    ns3_bake_repo: http://code.nsnam.org/bake
    bake_dir: '{{ ansible_env.HOME }}/deployed/bake'
    dce_linux_ver: 1.5
    dce_mptcp_net_next_sim_ver: 3.11.0
    dce_mptcp_net_next_sim_ver_major: 3.11
    dce_mptcp_repo: git://github.com/multipath-tcp/mptcp.git
    dce_mptcp_branch: mptcp_v0.88
  roles:
    - common
    - ns3dce
    - ns3mptcp
