- debug: var=output
- name: get bake script
  hg: repo="{{ ns3_bake_repo }}" dest="{{ bake_dir }}"
  environment: "{{ bake_env }}"

- name: create dce directory
  file:  path="{{ dce_dir }}" state=directory follow=yes

- name: check missing packages
  register: output
  command: chdir="{{ dce_dir }}" bake.py check
  environment: "{{ bake_env }}"
- debug: var=output

- name : debug environments
  register: output
  command: chdir="{{ dce_dir }}" /usr/bin/env
  environment: "{{ bake_env }}"

- name: configure, download and build dce
  command: chdir="{{ dce_dir }}" {{ item }}
  with_items:
  - bake.py configure -e "dce-linux-{{ dce_linux_ver }}"
  - bake.py download
  - bake.py build -vvv
  environment: "{{ bake_env }}"
