- name: install common Debian packages
  sudo: true
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
  - build-essential
  - zlib1g-dev
  - kernel-package
  - autoconf
  - automake
  - pkg-config
  - git
  - mercurial
  - libncurses5-dev
  - ethtool
  - xserver-xorg
  - libdb-dev
  - bison
  - flex
  - libssl-dev
  - python-bzrlib
  - bzr
  - tcpdump
  - screen
  - zsh
